# LIBRARIES:

## 1. Pandas
* **What it is:** The primary library for data manipulation and analysis.
* **Core Concept:** It provides a powerful, two-dimensional data structure called the **DataFrame**, 
    which is essentially a flexible table (like a spreadsheet or a SQL table) you can program with.
* **Use for:** Reading and writing data (from CSV, Excel, SQL databases, etc.), cleaning messy data, 
    filtering, sorting, grouping, merging, and reshaping data.

---

## 2. Numpy (Numerical Python) 🔢
* **What it is:** The fundamental library for numerical and scientific computing.
* **Core Concept:** It provides a highly efficient array object called the **ndarray** (N-dimensional array). 
    This allows for fast, vectorized mathematical operations on large sets of numbers, which is 
    much faster than using standard Python lists.
* **Use for:** Linear algebra, statistical operations, random number generation, and any heavy-duty math. 
    Pandas is built directly on top of NumPy; the columns in a Pandas DataFrame are often NumPy arrays.

---

## 3. Matplotlib 📊
* **What it is:** The original and most widely used data visualization library.
* **Core Concept:** It's a low-level, highly customizable "plotting engine." It gives you 
    fine-grained control over every single element of your charts (like axes, labels, colors, and layout).
* **Use for:** Creating all standard types of static plots: line charts, bar charts, histograms, 
    scatter plots, etc. It's the foundation for many other plotting libraries.

---

## 4. Seaborn 🎨
* **What it is:** A high-level statistical data visualization library *based on* Matplotlib.
* **Core Concept:** Seaborn is a "wrapper" for Matplotlib. It simplifies the process of creating complex, 
    common statistical plots and makes them look much more modern and attractive by default.
* **Use for:** Creating beautiful heatmaps, pair plots, violin plots, and regression plots. 
    It integrates perfectly with Pandas DataFrames, letting you create complex visualizations 
    with just one or two lines of code.

---
# SYLLABUS
1. NumPy: arrays,array operations,indexing,reshaping<br>
2. Pandas: DataFrame operations,indexing,merging,grouping<br>
3. Matplotilb: basic plotting,figures and axes<br>
4. Seaborn: statistical data visualization<br>
---

In [5]:
import numpy as np
list1=[[1,2,3],[4,5,6]]
print(list1)
print(list1[0][0]) #its a sequential data type and not a 2D array
print(np.__version__)

# 1. Display shape
arr1=np.array(list1)
print("Array:\n",arr1)
print(arr1[0][0])
print("Shape:",arr1.shape) #(rows,column)
print(arr1.ndim)
print(type(arr1))

[[1, 2, 3], [4, 5, 6]]
1
2.2.3
Array:
 [[1 2 3]
 [4 5 6]]
1
Shape: (2, 3)
2
<class 'numpy.ndarray'>


In [13]:
import numpy as np
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[1,2],[3,4],[7,8]])

ar3=np.dot(ar1,ar2) #dot product
m3=ar1 @ ar2
print(ar3)
print("\n",m3)

[[28 34]
 [61 76]]

 [[28 34]
 [61 76]]


In [11]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

arr2=arr1.reshape(3,2) #it works
print(arr2)
arr2=arr1.reshape(6,1) #it works as the  dimensions doesnt exceed beyond the multiplication of the matrices eg. 2*3=6
print(arr2)
arr2=arr1.reshape(1,6) #it works
print(arr2)

#arr2=arr1.reshape(3,3) #it doesnt work
#arr2=arr1.reshape(3,1) #it doesnt work
#print(arr2) #it doesnt work

[[1 2 3]
 [4 5 6]]
2
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]


In [ ]:
import numpy as np #Range function
ar4=np.arange(5,20,2) #start,stop-1,step
ar4

array([ 5,  7,  9, 11, 13, 15, 17, 19])

# PANDAS
* It is one of the usefull and powerfull libraries for data cleaning,manipulation, and data analysis
* There are two types of Pandas data structure in Pandas:
 # 1. Series<br> 
    When we have data in one dimensional then series is best eg. pd.series
 # 2. Data Frame<br> 
    When we have data with more than one dimension then data frame is best eg. pd.dataframe like csv,excel files
    

In [4]:
import pandas as pd

# List of lists: each inner list is a row
data = [
    ['Ishant', 88, 90, 82],
    ['Ravi', 92, 85, 89],
    ['Neha', 79, 88, 84],
    ['Simran', 93, 91, 86],
    ['Amit', 85, 76, 80]
]

# Convert list to DataFrame
df = pd.DataFrame(data, columns=['Name', 'Maths', 'Science', 'English'])
print("=== DataFrame Created from List ===")
print(df)


=== DataFrame Created from List ===
     Name  Maths  Science  English
0  Ishant     88       90       82
1    Ravi     92       85       89
2    Neha     79       88       84
3  Simran     93       91       86
4    Amit     85       76       80


In [7]:
import pandas as pd

# Step 1: Create a dictionary
data = {
    'Name': ['Ishant', 'Ravi', 'Neha', 'Simran', 'Amit'],
    'Maths': [88, 92, 79, 93, 85],
    'Science': [90, 85, 88, 91, 76],
    'English': [82, 89, 84, 86, 80]
}

# Step 2: Convert dictionary to DataFrame
df = pd.DataFrame(data)

print("=== DataFrame Created from Dictionary ===")
print(df)


=== DataFrame Created from Dictionary ===
     Name  Maths  Science  English
0  Ishant     88       90       82
1    Ravi     92       85       89
2    Neha     79       88       84
3  Simran     93       91       86
4    Amit     85       76       80


In [13]:
import pandas as pd
import numpy as np  # used for generating random numbers

# Step 1: Set a seed (optional, for reproducibility)
np.random.seed(42)

# Step 2: Create a DataFrame with random numbers
df = pd.DataFrame(
    np.random.randint(50, 100, size=(5, 4)),  # 5 rows, 4 columns, values between 50 and 99
    columns=['Maths', 'Science', 'English', 'Computer']
)

# Step 3: Add names to identify rows
df['Name'] = ['Ishant', 'Ravi', 'Neha', 'Simran', 'Amit']

print("=== Random DataFrame ===")
print(df)

print("\n=== Random DataFrame After Rearranging ===")
df = df[['Name', 'Maths', 'Science', 'English', 'Computer']]
print(df)

=== Random DataFrame ===
   Maths  Science  English  Computer    Name
0     88       78       64        92  Ishant
1     57       70       88        68    Ravi
2     72       60       60        73    Neha
3     85       89       73        52  Simran
4     71       51       73        93    Amit

=== Random DataFrame After Rearranging ===
     Name  Maths  Science  English  Computer
0  Ishant     88       78       64        92
1    Ravi     57       70       88        68
2    Neha     72       60       60        73
3  Simran     85       89       73        52
4    Amit     71       51       73        93


# Matplotlib<br>
Matplotlib is a Python library for data visualization.<br>
It provides tools to create static, interactive, and animated plots and charts from data

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns