# CREATING NUMP-Y/N -D ARRAYS:

In [5]:
import numpy as np
list1=[[1,2,3,4,5],[6,7,8,9,10]]
ar=np.array(list1)
print(ar)
type(ar)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


numpy.ndarray

In [7]:
ar1=np.zeros((2,5))
print(ar1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
ar2=np.ones((2,3))
ar2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
ar3=np.identity(5)
ar3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
import numpy as np
ar4=np.arange(5,20,2)
ar4

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
ar5=np.arange(5,21,2)
ar5

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
ar6=np.linspace(10,20,10)#lower range,upper range ,gap 
ar6

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [21]:
ar7=np.copy(ar5)
ar7

array([ 5,  7,  9, 11, 13, 15, 17, 19])